language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - tail -f build/logs/clover.xml -n50
  - php vendor/bin/coveralls -v